#! /bin/bash
# FS QA Test No. 256
#
# what am I here for?
#
#-----------------------------------------------------------------------
# Copyright (c) 2011 YOUR NAME HERE.  All Rights Reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it would be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write the Free Software Foundation,
# Inc.,  51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#-----------------------------------------------------------------------
#
# creator
owner=aditya.dani@gmail.com

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!
trap "_cleanup; exit \$status" 0 1 2 3 15

_cleanup()
{
    cd /
    rm -f $tmp.*
}

# get standard environment, filters and checks
. ./common.rc
. ./common.filter
. ./common.snapshot

# real QA test starts here

# Modify as appropriate.
_supported_fs generic
_supported_os IRIX Linux

N=4
cd $TEST_DIR
for s in $(btrfs subvolume list . | while read a b c d e f g ; do (echo $g) done) ; do
    btrfs subvolume delete $s > /dev/null 
done
cd - > /dev/null
for n in $( seq 1 $N ) ; do
    echo "$n"
   _snapshot_test || exit 1
done
_lstest
for n in $( seq 1 $N ) ; do
    _lstest $n
done

#if [ $N = 0] ; then
#    umount $TEST_DIR || exit 1
#    fsck $TEST_DEV
#    mount $TEST_DEV $TEST_DIR || exit 1
#else
#    for n in $( seq 1 $N ) ; do
#	$0 fsck $n 2> /dev/null
#    done
#fi

# optional stuff if your test has verbose output to help resolve problems
#echo
#echo "If failure, check $seq.full (this) and $seq.full.ok (reference)"

# success, all done
status=0
exit 0
